[package]
name = "steamcmd-2fa"
version = "0.2.0"
edition = "2021"

[dependencies]
simple-steam-totp = "0.1.0"
clap = { version = "4.5.2", features = ["derive","env"] }
shellwords = "1.1.0"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
